#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL
 
#define POSITION_ATTRIB_LOCATION 0
#define CAMERA_MATRIX_ATTRIB_LOCATION 1
#define COLOR_ATTRIB_LOCATION 2
#define TEXTURE_COORD_ATTRIB_LOCATION 3
#define TEXTURE_UNIFORM_LOCATION 0

#define TEXT_COLOR_UNIFORM_LOCATION 4
 
#endif // PREAMBLE_GLSL